### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bryonglodencissp**
Adding screenshots

### CODE REVIEW

**Comment by ahcho0819** [comment]
@bryongloden What is "https://live.staticflickr.com"? Is there official Synopsys account on the hosting site?

**Comment by bryonglodencissp** [comment]
@ahcho0819 That is a professional Flickr hosting site.

**Comment by bryonglodencissp** [comment]
@ahcho0819 Do you mean is the Flickr account "linked" to an synopsys.com email address?

**Comment by ahcho0819** [comment]
@bryonglodencissp Not "linked" to an synpsys.com email address, but is it an official synopsys account that we can use. If it is your personal account or someone else, then wouldn't be there a chance that the person might leave in the future and we can't use the account anymore?

**Comment by bryonglodencissp** [comment]
Can you determine how you want to manage the photos and add a few screenshots @ahcho0819?

**Comment by ahcho0819** [comment]
One way to add photos and embed them in the ReadMe is to store the screenshots in the repo and directly reference them from the ReadMe.

**Pull request closed without merging**
